//html markup copied from http://www.ujafedny.org/

var content = '<select name="division" id="division-select">'
    + '<option value="">Join a Group</option>'
    
    + '<option value="/emerge/">Emerging Leaders &amp; Philanthropists</option>'
    
    + '<option value="/entertainment-media-communications/">Entertainment, Media &amp; Communications</option>'
    
    + '<option value="/healthcare-division/">Healthcare Division</option>'
    
    + '<option value="/long-island/">Long Island</option>'
    
    + '<option value="/manhattan-division/">Manhattan Division</option>'
    
    + '<option value="/philanthropic-leadership-group/">Philanthropic Leadership Group</option>'
    
    + '<option value="/real-estate/">Real Estate &amp; Allied Trades Division</option>'
    
    + '<option value="/russian-division/">Russian Division</option>'
    
    + '<option value="/the-lawyers-division/">The Lawyers Division</option>'
    
    + '<option value="/wall-street-financial-services-division/">Wall Street &amp; Financial Services Division</option>'
    
    + '<option value="/westchester/">Westchester</option>'
    
    + '<option value="/womens-philanthropy/">Women s Philanthropy</option>'
        
+ '</select>		'
        
+ '<ul id="nav">'
   + ' <li>'
    + '<a href="/" class="t"><span class="l"></span><span class="r"></span><span class="cufon cufon-canvas" style="width: 37px; height: 17px; "><canvas width="42" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Home</span></span></a>'
    + '</li>'
    + '<li>'
    + '<a href="/who-we-are/" class="t"><span class="l"></span><span class="r"></span><span class="cufon cufon-canvas" style="width: 32px; height: 17px; "><canvas width="41" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Who </span></span><span class="cufon cufon-canvas" style="width: 24px; height: 17px; "><canvas width="33" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">We </span></span><span class="cufon cufon-canvas" style="width: 21px; height: 17px; "><canvas width="26" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Are</span></span></a>            '
    + '<ul>'
    + '<li class="t">'
    + '<a href="/our-mission/" class="f">Our Mission</a></li>'
    + '<li>'
    + '<a href="/our-leadership/" class="f">Our Leadership</a></li>'
    + '<li>'
    + '<a href="/what-we-do/" class="f">What We Do</a></li>'
    + '<li class="b">'
    + '<a href="/annual-report/" class="f">Annual Report</a></li>'
    + '</ul>'
    + '</li>'
    + '<li>'
    + '<a href="/uja-federation-news/" class="t"><span class="l"></span><span class="r"></span><span class="cufon cufon-canvas" style="width: 38px; height: 17px; "><canvas width="47" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">News </span></span><span class="cufon cufon-canvas" style="width: 28px; height: 17px; "><canvas width="37" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">and </span></span><span class="cufon cufon-canvas" style="width: 36px; height: 17px; "><canvas width="42" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Views</span></span></a>'
    + '<ul>'
    + '<li class="t">'
    + '<a href="/uja-federation-news/" class="f">UJA-Federation News</a></li>'
    + '<li>'
    + '<a href="/press-room/" class="f">Press Room</a></li>'
    + '<li>'
    + '<a href="/around-the-web/" class="f">Around the Web</a></li>'
    + '<li class="b">'
    + '<a href="/the-flame-spring-2011/" class="f">The Flame Newsletter</a></li>'
    + '</ul>'
    + '</li>'
    + '<li>'
    + '<a href="/get-involved/" class="t"><span class="l"></span><span class="r"></span><span class="cufon cufon-canvas" style="width: 26px; height: 17px; "><canvas width="35" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Get </span></span><span class="cufon cufon-canvas" style="width: 52px; height: 17px; "><canvas width="57" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Involved</span></span></a>'
    + '<ul>'
    + '<li class="t">'
    + '<a href="/join-a-group/" class="f">Join a Group</a></li>'
    + '<li>'
    + '<a href="/attend-events/" class="f">Attend Events</a></li>'
    + '<li>'
    + '<a href="/volunteer/" class="f">Volunteer</a></li>'
    + '<li>'
    + '<a href="/missions/" class="f">Missions</a></li>'
    + '<li>'
    + '<a href="/israel-experience/" class="f">Israel Experience</a></li>'
    + '<li>'
    + '<a href="/advocacy/" class="f">Advocacy</a></li>'
    + '<li class="b">'
    + '<a href="/social-media/" class="f">Social Media</a></li>'
    + '</ul>'
    + '</li>'
    + '<li>'
    + '<a href="/make-a-gift/" class="t"><span class="l"></span><span class="r"></span><span class="cufon cufon-canvas" style="width: 39px; height: 17px; "><canvas width="48" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Make </span></span><span class="cufon cufon-canvas" style="width: 13px; height: 17px; "><canvas width="21" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">a </span></span><span class="cufon cufon-canvas" style="width: 23px; height: 17px; "><canvas width="31" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Gift</span></span></a>'
    + '<ul>'
    + '<li class="t">'
    + '<a href="/make-a-donation/" class="f">Make a Donation</a></li>'
    + '<li>'
    + '<a href="/pay-your-pledge/" class="f">Pay Your Pledge</a></li>'
    + '<li>'
    + '<a href="/sustainer-program/" class="f">Sustainer Program</a></li>'
    + '<li>'
    + '<a href="/planned-giving-endowments/" class="f">Planned Giving</a></li>'
    + '<li>'
    + '<a href="/tribute-cards/" class="f">Tribute Cards</a></li>'
    + '<li class="b">'
    + '<a href="/corporate-partners-circle/" class="f">Corporate Partners</a></li>'
    + '</ul>'
    + '</li>'
    + '<li class="l">'
    + '<a href="/find-help/" class="t"><span class="l"></span><span class="r"></span><span class="cufon cufon-canvas" style="width: 32px; height: 17px; "><canvas width="40" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Find </span></span><span class="cufon cufon-canvas" style="width: 29px; height: 17px; "><canvas width="34" height="17" style="top: 1px; left: -1px; "></canvas><span class="cufon-alt">Help</span></span></a>'
    + '<ul>'
    + '<li class="t">'
    + '<a href="/network-agencies-directory/" class="f">Network Agencies Directory</a></li>'
    + '<li>'
    + '<a href="/new-york-times-neediest-cases/" class="f">Success Stories</a></li>'
    + '<li class="b">'
    + '<a href="/scholarships-and-fellowships/" class="f">Scholarships</a></li>'
    + '</ul>'
    + '</li>'
+ '</ul>';

document.getElementById('primary').innerHTML = content;

        